### PR TITLE
Run build on all branches

### PR DESCRIPTION
**Pull request by alessiamarcolini**

### CODE REVIEW

**Review by ernestoarbitrio — COMMENTED** [review]
Can you explain why this change? I don't see any needs for running tests on other branches different from master

**Comment by alessiamarcolini** [comment]
When we were using TravisCI this was the behavior, then when we switched to GH we dropped it. Was this intentional? I noticed this while updating the supplementary material of the histolab paper

**Comment by ernestoarbitrio** [comment]
> When we were using TravisCI this was the behavior, then when we switched to GH we dropped it. Was this intentional? I noticed this while updating the supplementary material of the histolab paper

It's intentional cause we do not create ad-hoc branched where we wanna run the CI, the only way to create branch is via a PR and on the PR we have the rule on the workflow file

**Comment by alessiamarcolini** [comment]
Alright, I will close this PR

**Pull request closed without merging**
