### PR TITLE
fix bug about pixel overlap of adjacent tiles

### PR DESCRIPTION
**Pull request by nipeone**
## Types of Changes

- [ ] Core
- [x] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Documentation

## Issues Fixed or Closed by This PR

* Fixes: 
https://github.com/histolab/histolab/issues/370

## Checklist

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [CONTRIBUTING](https://github.com/histolab/histolab/blob/master/CONTRIBUTING.md) document.
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by alessiamarcolini** [comment]
Hi @nipeone, congrats on your first contribution to Histolab 🎉

> but if i create new PR,need i create unit test about this issue?

For this issue, an integration test would be better. Please note that we are testing the Tilers using the `locate_tiles` method (better to visualize, easier to test) https://github.com/histolab/histolab/blob/master/tests/integration/test_tiler.py#L331
So you could write a new test using only 1 or 2 fixtures following the test structure of `it_locates_tiles_on_the_slide` and changing the value of the parameter `pixel_overlap`.

Of course, if you need guidance on this we are here ❤️

Alessia

**Comment by nipeone** [comment]
so sad,it's a little hard to me add integration test in test_tiler.py,  i have tried.

**Comment by nipeone** [comment]
so sad,it's a little hard to me add integration test in test_tiler.py,  i have tried.

**Comment by alessiamarcolini** [comment]
Hey @nipeone, I added the missing integration test, no problem.

@ernestoarbitrio however, this PR will fail again for the same reason as #371

**Comment by ernestoarbitrio** [comment]
> Hey @nipeone, I added the missing integration test, no problem.
> 
> @ernestoarbitrio however, this PR will fail again for the same reason as #371

now it should be ok

**Review by ernestoarbitrio — APPROVED** [review]

**Comment by nipeone** [comment]
> Hey @nipeone, I added the missing integration test, no problem.
> 
> @ernestoarbitrio however, this PR will fail again for the same reason as #371
that's great!!!

**Pull request merged**
