### PR TITLE
Allow slide name to contain dot

### PR DESCRIPTION
**Pull request by kheffah**
If a slide name contains one or more dots in its middle, other than the extension, make sure to retain that in the ``self.name`` property of ``Slide``.

### CODE REVIEW

**Comment by kheffah** [comment]
@alessiamarcolini Thank you. All done.

**Comment by ernestoarbitrio** [comment]
@kheffah, this PR will be merged ASAP (after @alessiamarcolini review) and then it will be included in the `0.2.6` version that will be released today or tomorrow. Thanks for your contribution 😄 ❤️

**Comment by kheffah** [comment]
> @kheffah, this PR will be merged ASAP (after @alessiamarcolini review) and then it will be included in the `0.2.6` version that will be released today or tomorrow. Thanks for your contribution

Sure thing :)

**Review by alessiamarcolini — APPROVED** [review]
LGTM!! 🙌 

Thank you very much @kheffah for the contribution 🚀

**Pull request merged**
